const smartphoneRecommendation = {
  content_id: "top-5-best-mobile-phones-under-20000-tk-12823",
  title: "Top 5 Best mobile phones under 20000 taka in 2023 (Jul-Aug)",
  img_url:
    "https://firebasestorage.googleapis.com/v0/b/mobile-seller-bd.appspot.com/o/trends%2Fandroid-phone-2048px-0004-2x1-1.webp?alt=media&token=cd143aa8-934b-4c62-a7a2-ae35a8b87329",
  short_description:
    "Discover the top 5 budget-friendly mobile phones under 20000 taka in Bangladesh for 2023. Featuring brands like Xiaomi, Tecno, Realme, and Motorola with impressive features such as AMOLED displays, high-resolution cameras, and powerful processors.",
  tag: [
    "Mobile Phones",
    "Budget Smartphones",
    "Best Smartphones",
    "Smartphone Recommendations",
    "Bangladesh",
    "Top Mobiles",
    "Affordable Phones",
    "20000 Taka",
    "2023",
  ],
  content_type: "Trends",
  meta_description:
    "Looking for the best budget-friendly smartphones in Bangladesh? Check out our list of top 5 mobile phones under 20000 taka for 2023. Featuring brands like Xiaomi, Tecno, Realme, and Motorola, with impressive features like AMOLED displays, high-resolution cameras, and powerful processors.",
  description: [
    {
      no: 1,
      brand: "Xiaomi",
      model: "Xiaomi Redmi Note 12 4G",
      display: `6.67" AMOLED | Full HD+ | 120Hz`,
      processor: "Snapdragon 685",
      main_camera: "50MP+8MP+2MP",
      front_camera: "13MP",
      storage: "4GB | 128GB",
      battery: "5000 mAh | 33W",
      price: "19,999 BDT.",
      id: "xiaomi-redmi-note-12-4g-3980",
      rec_for: "",
      img_url: "",
    },
    {
      no: 2,
      brand: "Xiaomi",
      model: "Xiaomi Poco X5",
      display: '6.67" Super AMOLED | Full HD+ | 120Hz',
      processor: "Snapdragon 695 5G",
      main_camera: "48MP+8MP+2MP",
      front_camera: "13MP",
      storage: "6GB | 128GB",
      battery: "5000 mAh | 33W",
      price: "22,000 BDT. (approx)",
      id: "xiaomi-poco-x5-8144",
      rec_for: "",
      img_url: "",
    },
    {
      no: 3,
      brand: "Tecno",
      model: "Tecno Spark 10 Pro",
      display: '6.8" IPS LCD | Full HD+ | 90Hz',
      processor: "Mediatek Helio G88",
      main_camera: "50MP+0.8MP",
      front_camera: "32MP",
      storage: "8GB | 128GB",
      battery: "5000 mAh | 18W",
      price: "17,990 BDT.",
      id: "tecno-spark-10-pro-7731",
      rec_for: "",
      img_url: "",
    },
    {
      no: 4,
      brand: "Realme ",
      model: "Realme 10",
      display: '6.64" Super AMOLED | Full HD+ | 90Hz',
      processor: "Mediatek MT8781 Helio G99",
      main_camera: "50MP+2MP",
      front_camera: "16MP",
      storage: "8GB | 128GB",
      battery: "5000 mAh | 33W",
      price: "21,000 BDT. (approx)",
      id: "realme-10-7884",
      rec_for: "",
      img_url: "",
    },
    {
      no: 5,
      brand: "Motorola",
      model: "Motorola Moto G62 5G",
      display: '6.5" IPS LCD | Full HD+ | 120Hz',
      processor: "Snapdragon 480+ 5G",
      main_camera: "50MP+8MP+2MP",
      front_camera: "16MP",
      storage: "4GB | 128GB",
      battery: "5000 mAh | 15W",
      price: "20,000 BDT. (approx)",
      id: "motorola-moto-g62-5g-5283",
      rec_for: "",
      img_url: "",
    },
  ],
};
